"""Database models for ERA Assistant."""
import uuid
from sqlalchemy import create_engine, Column, Integer, String, DateTime, Text, JSON, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
import enum

Base = declarative_base()


class RecordStatus(str, enum.Enum):
    """Status values matching Feishu Base options."""
    SUBMITTED = "Submitted"
    PROCESSING = "Processing"
    READY_FOR_ANALYSIS = "Ready for Analysis"
    ANALYZING = "Analyzing"
    SCORED = "Scored"
    EMAILING = "Emailing"
    DONE = "Done"
    FAILED = "Failed"


class Record(Base):
    """Tracks each report submission through the workflow."""

    __tablename__ = "records"

    id = Column(Integer, primary_key=True, index=True)

    # Public access token (UUID4) for report viewer links
    view_token = Column(String(36), unique=True, index=True, nullable=True, default=lambda: str(uuid.uuid4()))

    # Feishu Base reference
    feishu_record_id = Column(String(100), unique=True, index=True, nullable=False)

    # Employee info (from Feishu)
    employee_name = Column(String(200), nullable=False)
    employee_email = Column(String(200), nullable=False)

    # File info
    file_token = Column(String(200), nullable=False)  # Feishu file token for download
    file_name = Column(String(500))

    # 预设的飞书表格链接（可选，如有则跳过导入）
    report_link = Column(String(500), nullable=True)

    # Feishu document link (after upload to Drive)
    feishu_doc_url = Column(String(500), nullable=True)

    # Status tracking
    status = Column(
        Enum(RecordStatus, values_callable=lambda x: [e.value for e in x]),
        default=RecordStatus.SUBMITTED,
        nullable=False
    )

    # Excel extraction results
    sheet_name = Column(String(100), nullable=True)
    total_rows = Column(Integer, nullable=True)
    total_cols = Column(Integer, nullable=True)
    raw_text = Column(Text, nullable=True)  # pandas to_string() output for AI analysis

    # Analysis results (array of 3 judge scores)
    analysis_results = Column(JSON, nullable=True)
    # Example: [
    #   {
    #     "judge": "Judge 1 (Qwen)",
    #     "success": true,
    #     "总分": 85,
    #     "等级": "B",
    #     "各维度评分": {...},
    #     "主要问题": [...],
    #     "改进建议": [...]
    #   },
    #   ... Judge 2, Judge 3
    # ]

    # Final calculated score (from main judge)
    final_score = Column(JSON, nullable=True)
    # Example: {
    #   "总分": 85,
    #   "等级": "B",
    #   "各维度平均分": {...},
    #   "汇总主要问题": [...],
    #   "汇总改进建议": [...]
    # }

    # Email content generated by main judge
    email_content = Column(Text, nullable=True)

    # Error tracking (for Failed status)
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    email_sent_at = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self):
        return f"<Record(id={self.id}, feishu_id={self.feishu_record_id}, status={self.status})>"
